# Generated by Django 2.2.6 on 2019-11-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='pub_date',
        ),
    ]
