# Generated by Django 2.2.6 on 2019-11-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0003_auto_20191117_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
