# Generated by Django 2.2.1 on 2019-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0004_auto_20191117_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='img',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
