# Generated by Django 2.2.1 on 2019-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0007_auto_20191118_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='cnn_coin'),
        ),
    ]
