# Generated by Django 2.2.1 on 2019-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0008_auto_20191119_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='cnn_coin'),
        ),
    ]
