# Generated by Django 2.2.1 on 2019-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0010_imagemodel_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
