# Generated by Django 2.2.1 on 2019-11-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0011_auto_20191120_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
