# Generated by Django 2.2.1 on 2019-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0012_auto_20191120_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='accuracy',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='cnn_coin/'),
        ),
    ]
