# Generated by Django 2.2.1 on 2019-11-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_coin', '0013_auto_20191124_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='cnn_coin'),
        ),
    ]
